// <auto-generated />
using System;
using GymClub.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymClub.Migrations
{
    [DbContext(typeof(GymContext))]
    [Migration("20260828230201_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymClub.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            Name = "Chest"
                        },
                        new
                        {
                            ExerciseId = 2,
                            Name = "Back"
                        },
                        new
                        {
                            ExerciseId = 3,
                            Name = "Legs"
                        },
                        new
                        {
                            ExerciseId = 4,
                            Name = "Shoulders"
                        },
                        new
                        {
                            ExerciseId = 5,
                            Name = "Biceps & Triceps"
                        },
                        new
                        {
                            ExerciseId = 6,
                            Name = "Cardio"
                        },
                        new
                        {
                            ExerciseId = 7,
                            Name = "Rest Day"
                        });
                });

            modelBuilder.Entity("GymClub.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubscriptionEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SubscriptionStart")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            IsAdmin = true,
                            Name = "Ahmad Nassar",
                            Password = "admin123",
                            SubscriptionEnd = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionStart = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberId = 2,
                            IsAdmin = false,
                            Name = "Khaled Yousef Amer",
                            Password = "123",
                            SubscriptionEnd = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionStart = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MemberId = 3,
                            IsAdmin = false,
                            Name = "Sara Adel Hamdan",
                            Password = "456",
                            SubscriptionEnd = new DateTime(2027, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionStart = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GymClub.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("MemberId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            DayOfWeek = 0,
                            ExerciseId = 1,
                            MemberId = 2
                        },
                        new
                        {
                            ScheduleId = 2,
                            DayOfWeek = 1,
                            ExerciseId = 2,
                            MemberId = 2
                        },
                        new
                        {
                            ScheduleId = 3,
                            DayOfWeek = 2,
                            ExerciseId = 3,
                            MemberId = 2
                        },
                        new
                        {
                            ScheduleId = 4,
                            DayOfWeek = 3,
                            ExerciseId = 4,
                            MemberId = 2
                        },
                        new
                        {
                            ScheduleId = 5,
                            DayOfWeek = 4,
                            ExerciseId = 5,
                            MemberId = 2
                        },
                        new
                        {
                            ScheduleId = 6,
                            DayOfWeek = 5,
                            ExerciseId = 6,
                            MemberId = 2
                        },
                        new
                        {
                            ScheduleId = 7,
                            DayOfWeek = 6,
                            ExerciseId = 7,
                            MemberId = 2
                        },
                        new
                        {
                            ScheduleId = 8,
                            DayOfWeek = 0,
                            ExerciseId = 2,
                            MemberId = 3
                        },
                        new
                        {
                            ScheduleId = 9,
                            DayOfWeek = 1,
                            ExerciseId = 1,
                            MemberId = 3
                        },
                        new
                        {
                            ScheduleId = 10,
                            DayOfWeek = 2,
                            ExerciseId = 6,
                            MemberId = 3
                        },
                        new
                        {
                            ScheduleId = 11,
                            DayOfWeek = 3,
                            ExerciseId = 3,
                            MemberId = 3
                        },
                        new
                        {
                            ScheduleId = 12,
                            DayOfWeek = 4,
                            ExerciseId = 4,
                            MemberId = 3
                        },
                        new
                        {
                            ScheduleId = 13,
                            DayOfWeek = 5,
                            ExerciseId = 5,
                            MemberId = 3
                        },
                        new
                        {
                            ScheduleId = 14,
                            DayOfWeek = 6,
                            ExerciseId = 7,
                            MemberId = 3
                        });
                });

            modelBuilder.Entity("GymClub.Models.Schedule", b =>
                {
                    b.HasOne("GymClub.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymClub.Models.Member", "Member")
                        .WithMany("Schedules")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymClub.Models.Member", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
